/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EVEMarkup: typeof import('./src/components/EVEMarkup.vue')['default']
    IconEOLAnimated: typeof import('./src/components/icons/IconEOLAnimated.vue')['default']
    IconEvexcel: typeof import('./src/components/icons/IconEvexcel.vue')['default']
    LanguageSwitch: typeof import('./src/components/LanguageSwitch.vue')['default']
    LightSwitch: typeof import('./src/components/LightSwitch.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SSOLogin: typeof import('./src/components/SSOLogin.vue')['default']
  }
}
