name: Tests
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
jobs:
  unittest:
    name: Unit Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
      - name: Run Vitest unit tests
        run: npm run test:unit
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: |
            test-results/
          retention-days: 30

  # disabled until v1.0.0 release
  # e2etest:
  #   name: End-to-end Tests
  #   needs: unittest
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build the project
  #       run: npm run build
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: npm run test:e2e
  #     - name: Upload test results
  #       uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: test-results
  #         path: |
  #           playwright-report/
  #         retention-days: 30
